export default {
    yoyo : {url:"yoyo.PNG",title:"YOYO.eco",text:["Plateforme communautaire de recyclage permettant de gagner des points échangeables dans la boutique en ligne.", "Création et gestion de boutique", "Système de recommandation", "React front-end","PHP back-end","UX Design"], path:"https://yoyo.eco/", git:""},
    portailsante : {url:"portailsante.PNG",title:"Portail Santé ARS",text:["Portail permettant le dépot, la consultation des offres d'actions de sensibilisation et l'organisation du service sanitaire des étudiants de santé.","Gestion d'offres de stage", "Gestion et union de plannings", "React front-end","PHP back-end","UX Design"], photoFit:true, git:"", path:"https://service-sanitaire-grand-est.fr/"},
    flappybird : {url:"flappybird.PNG",title:"FlappyBird IA",text:["Jeu Flappy Bird avec une IA intégrée permettant d'esquiver les tuyaux.", "Création de jeu avec IA","p5.js","Feedforward Neural Network","Stratégie évolutionnaire"], path:"https://quentin-parmentier.github.io/flappyBird/", git:"https://github.com/quentin-parmentier/flappyBird"},
    qlearning : {url:"qlearning.PNG",title:"GO Back home",text:["Un agent (voiture) essaye de rentrer chez elle en esquivant les travaux","Apprentissage par renforcement", "Q-Learning","Résolution de parcours"], path:"https://quentin-parmentier.github.io/qlearning/", git:"https://github.com/quentin-parmentier/qlearning"},
    maze : {url:"maze.PNG",title:"Maze Creator and Solver",text:["Interface permettant de créer un labyrinthe avec une IA le résolvant.", "Création de jeu avec IA","Résolution de labyrinthe","Algorithme génétique"], path:"https://quentin-parmentier.github.io/Amazeing/", git:"https://github.com/quentin-parmentier/Amazeing"},
    nono : {url:"nono.PNG",title:"Nono le petit robot",text:["Projet Hackathon : Jeu sérieux sensibilisant les enfants à la robotique", "Création de jeu sérieux","Game design","Robotique","1ere place Hackathon"], path:"https://quentin-parmentier.github.io/nono/character_selection.html", git:"https://github.com/quentin-parmentier/nono"},
    component : {url:"component.PNG",title:"Components creator",text:["Librairie générant une page avec des composants à partir d'un fichier .json.","Rendu côté client avec Ajax", "Fichier de configuration .json", "100% responsive", "10 composants différents"], path:"", git:""},
    sportner : {url:"sportner.PNG",title:"Sportner",text:["Plateforme permettant de créer et rejoindre des évènements sportifs pour trouver des partenaires de sport.","OpenStreetMap & Leaflet","Gestion d'évènements","Recherche et géoposition","VueJS front-end","Laravel back-end"], path:"", git:"https://github.com/quentin-parmentier/sportnerGit"},
}
